"""Stub module for defusedxml.ElementTree."""

class ParseError(Exception): ...

class Element:
    text: str | None

    def findall(self, path: str, namespaces: dict[str, str] | None = ...) -> list[Element]: ...
    def get(self, key: str) -> str | None: ...

class ElementTree:
    def getroot(self) -> Element: ...

def parse(source: object) -> ElementTree: ...
